[package]
name = "rustpython"
version = "0.3.1"

[[module]]
name = "rustpython"
source = "target/wasm32-wasi/release/rustpython.wasm"
abi = "wasi"

[[command]]
name = "rustpython"
module = "rustpython"

[fs]
"/lib/rustpython" = "Lib"
