[package]
name = "rustpython-derive"
version = "0.3.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
rustpython-compiler = { workspace = true }
rustpython-derive-impl = { workspace = true }
syn = { workspace = true }
