[package]
name = "rustpython-compiler"
version = "0.3.1"
edition = "2021"

[dependencies]
rustpython-codegen = { workspace = true }
rustpython-compiler-core = { workspace = true }
rustpython-parser = { workspace = true }
